name: "⚙️ Tech Task - 기술 작업"
description: "리팩토링, 성능 개선, 인프라 작업 등"
title: "[TECH] "
labels: ["tech-task", "status-todo"]
assignees: []
body:
  - type: input
    id: task-title
    attributes:
      label: "⚙️ 기술 작업 제목"
      description: "수행할 기술 작업의 제목"
      placeholder: "예: Spring Cache 적용으로 조회 성능 개선"
    validations:
      required: true

  - type: dropdown
    id: task-type
    attributes:
      label: "🏷️ 작업 유형"
      description: "기술 작업의 유형"
      options:
        - "성능 최적화"
        - "리팩토링"
        - "보안 강화"
        - "인프라 개선"
        - "테스트 개선"
        - "문서화"
        - "기술 부채 해결"
    validations:
      required: true

  - type: textarea
    id: current-situation
    attributes:
      label: "📊 현재 상황"
      description: "개선이 필요한 현재 상황"
      placeholder: |
        현재 문제점:
        - 회원 조회 API 응답시간이 5초 소요
        - 동일한 데이터를 반복적으로 DB 조회
        - 캐시 미적용으로 인한 성능 저하
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: "💡 제안 솔루션"
      description: "문제 해결을 위한 구체적인 방안"
      placeholder: |
        제안 방안:
        - Spring Cache 적용 (@Cacheable)
        - Redis 연동으로 분산 캐시 구축
        - 캐시 무효화 전략 수립
    validations:
      required: true

  - type: textarea
    id: expected-outcome
    attributes:
      label: "🎯 기대 효과"
      description: "작업 완료 후 기대되는 개선 효과"
      placeholder: |
        기대 효과:
        - 응답시간 5초 → 1초로 개선
        - DB 부하 80% 감소
        - 사용자 경험 향상
    validations:
      required: true

  - type: textarea
    id: implementation-plan
    attributes:
      label: "🛠️ 구현 계획"
      description: "단계별 구현 계획"
      placeholder: |
        1단계: Cache 설정 및 기본 적용
        2단계: 캐시 무효화 로직 구현
        3단계: 성능 테스트 및 검증
        4단계: 모니터링 체계 구축
    validations:
      required: true

  - type: textarea
    id: risks-considerations
    attributes:
      label: "⚠️ 리스크 및 고려사항"
      description: "작업 진행 시 고려해야 할 리스크나 주의사항"
      placeholder: |
        리스크:
        - 캐시 불일치로 인한 데이터 정합성 문제
        - 메모리 사용량 증가
        
        고려사항:
        - 적절한 캐시 TTL 설정
        - 캐시 크기 제한
    validations:
      required: false